"""UI strings for the allergen and diabetic tags, 29 languages, in the order of KEYS.
Inserted into src/data/translations.ts by scripts/diet/apply_health_strings.py. Kurdish is Kurmanji in Latin script.
Written without native-speaker review (like ui_strings.py): have a reader of each language check them."""
KEYS = ('allergenContains', 'allergenNone', 'allergenCheck', 'allergenUnknown', 'allergenNote',
        'diabeticFriendly', 'diabeticBorderline', 'diabeticNot', 'diabeticNote',
        'allergenMilk', 'allergenEggs', 'allergenGluten', 'allergenNuts', 'allergenPeanuts', 'allergenSesame', 'allergenSoy',
        'allergenFish', 'allergenCrustaceans', 'allergenMolluscs', 'allergenCelery', 'allergenMustard', 'allergenLupin', 'allergenSulphites')
S = {
 'en': ("Contains", "No major allergens found", "No allergens found; check labels of bought items", "Allergens not assessed yet",
        "Worked out from the ingredients and steps; it may be incomplete and is not a guarantee. Read labels and ask about cross-contact.",
        "Diabetic-friendly (estimate)", "Moderate carbs or sugar (estimate)", "Not diabetic-friendly (estimate)",
        "An estimate from the nutrition estimate per serving; not medical advice. People with diabetes should ask a doctor or dietitian.",
        "Milk", "Eggs", "Gluten (wheat, barley, rye, oats)", "Tree nuts", "Peanuts", "Sesame", "Soy", "Fish", "Crustaceans", "Molluscs", "Celery", "Mustard", "Lupin", "Sulphites"),
 'ar': ("يحتوي على", "لا مسببات حساسية رئيسية", "لا مسببات حساسية ظاهرة؛ راجع ملصقات المكونات الجاهزة", "لم تُقيَّم مسببات الحساسية بعد",
        "مستنتجة من المكونات والخطوات وقد تكون ناقصة، وليست ضمانًا. اقرأ الملصقات واسأل عن التلوث التبادلي.",
        "مناسبة لمرضى السكري (تقدير)", "كربوهيدرات أو سكر معتدل (تقدير)", "غير مناسبة لمرضى السكري (تقدير)",
        "تقدير مبني على تقدير القيم الغذائية للحصة، وليس نصيحة طبية. على مرضى السكري استشارة الطبيب أو أخصائي التغذية.",
        "حليب", "بيض", "جلوتين (قمح وشعير وجاودار وشوفان)", "مكسرات", "فول سوداني", "سمسم", "صويا", "سمك", "قشريات", "رخويات", "كرفس", "خردل", "ترمس", "كبريتيت"),
 'fr': ("Contient", "Aucun allergène majeur trouvé", "Aucun allergène trouvé ; vérifiez les étiquettes des produits achetés", "Allergènes pas encore évalués",
        "Déduit des ingrédients et des étapes ; peut être incomplet et ne constitue pas une garantie. Lisez les étiquettes et renseignez-vous sur les contaminations croisées.",
        "Convient aux diabétiques (estimation)", "Glucides ou sucre modérés (estimation)", "Ne convient pas aux diabétiques (estimation)",
        "Estimation d'après les valeurs nutritionnelles estimées par portion ; pas un avis médical. Les personnes diabétiques doivent demander conseil à un médecin ou à un diététicien.",
        "Lait", "Œufs", "Gluten (blé, orge, seigle, avoine)", "Fruits à coque", "Arachides", "Sésame", "Soja", "Poisson", "Crustacés", "Mollusques", "Céleri", "Moutarde", "Lupin", "Sulfites"),
 'es': ("Contiene", "No se encontraron alérgenos principales", "No se encontraron alérgenos; revise las etiquetas de los productos comprados", "Alérgenos aún no evaluados",
        "Deducido de los ingredientes y los pasos; puede estar incompleto y no es una garantía. Lea las etiquetas y pregunte por la contaminación cruzada.",
        "Apto para diabéticos (estimación)", "Hidratos de carbono o azúcar moderados (estimación)", "No apto para diabéticos (estimación)",
        "Estimación a partir de la estimación nutricional por ración; no es consejo médico. Las personas con diabetes deben consultar a un médico o dietista.",
        "Leche", "Huevos", "Gluten (trigo, cebada, centeno, avena)", "Frutos de cáscara", "Cacahuetes", "Sésamo", "Soja", "Pescado", "Crustáceos", "Moluscos", "Apio", "Mostaza", "Altramuces", "Sulfitos"),
 'de': ("Enthält", "Keine Hauptallergene gefunden", "Keine Allergene gefunden; Etiketten gekaufter Zutaten prüfen", "Allergene noch nicht bewertet",
        "Aus Zutaten und Schritten abgeleitet; kann unvollständig sein und ist keine Garantie. Etiketten lesen und nach Kreuzkontamination fragen.",
        "Für Diabetiker geeignet (Schätzung)", "Mäßig viele Kohlenhydrate oder Zucker (Schätzung)", "Für Diabetiker nicht geeignet (Schätzung)",
        "Schätzung auf Grundlage der geschätzten Nährwerte pro Portion; kein medizinischer Rat. Menschen mit Diabetes sollten Ärztin, Arzt oder Ernährungsberatung fragen.",
        "Milch", "Eier", "Gluten (Weizen, Gerste, Roggen, Hafer)", "Schalenfrüchte", "Erdnüsse", "Sesam", "Soja", "Fisch", "Krebstiere", "Weichtiere", "Sellerie", "Senf", "Lupine", "Sulfite"),
 'it': ("Contiene", "Nessun allergene principale trovato", "Nessun allergene trovato; controlla le etichette degli ingredienti acquistati", "Allergeni non ancora valutati",
        "Dedotto da ingredienti e passaggi; può essere incompleto e non è una garanzia. Leggi le etichette e chiedi della contaminazione crociata.",
        "Adatto ai diabetici (stima)", "Carboidrati o zuccheri moderati (stima)", "Non adatto ai diabetici (stima)",
        "Stima basata sulla stima nutrizionale per porzione; non è un parere medico. Chi ha il diabete chieda al medico o al dietista.",
        "Latte", "Uova", "Glutine (frumento, orzo, segale, avena)", "Frutta a guscio", "Arachidi", "Sesamo", "Soia", "Pesce", "Crostacei", "Molluschi", "Sedano", "Senape", "Lupini", "Solfiti"),
 'tr': ("İçerir", "Başlıca alerjen bulunmadı", "Alerjen bulunmadı; satın alınan malzemelerin etiketlerini kontrol edin", "Alerjenler henüz değerlendirilmedi",
        "Malzemelerden ve adımlardan çıkarılmıştır; eksik olabilir ve garanti değildir. Etiketleri okuyun, çapraz bulaşmayı sorun.",
        "Diyabetliler için uygun (tahmin)", "Orta düzeyde karbonhidrat veya şeker (tahmin)", "Diyabetliler için uygun değil (tahmin)",
        "Porsiyon başına besin tahminine dayalı bir tahmindir; tıbbi tavsiye değildir. Diyabetliler doktora veya diyetisyene danışmalıdır.",
        "Süt", "Yumurta", "Gluten (buğday, arpa, çavdar, yulaf)", "Sert kabuklu yemişler", "Yer fıstığı", "Susam", "Soya", "Balık", "Kabuklular", "Yumuşakçalar", "Kereviz", "Hardal", "Acı bakla", "Sülfitler"),
 'ru': ("Содержит", "Основных аллергенов не найдено", "Аллергенов не найдено; проверяйте этикетки купленных продуктов", "Аллергены ещё не оценены",
        "Определено по ингредиентам и шагам; может быть неполным и не является гарантией. Читайте этикетки и спрашивайте о перекрёстном загрязнении.",
        "Подходит при диабете (оценка)", "Умеренно углеводов или сахара (оценка)", "Не подходит при диабете (оценка)",
        "Оценка на основе расчётной пищевой ценности на порцию; не медицинский совет. При диабете проконсультируйтесь с врачом или диетологом.",
        "Молоко", "Яйца", "Глютен (пшеница, ячмень, рожь, овёс)", "Орехи", "Арахис", "Кунжут", "Соя", "Рыба", "Ракообразные", "Моллюски", "Сельдерей", "Горчица", "Люпин", "Сульфиты"),
 'pt': ("Contém", "Nenhum alérgeno principal encontrado", "Nenhum alérgeno encontrado; verifique os rótulos dos ingredientes comprados", "Alérgenos ainda não avaliados",
        "Deduzido dos ingredientes e dos passos; pode estar incompleto e não é uma garantia. Leia os rótulos e pergunte sobre contaminação cruzada.",
        "Adequado para diabéticos (estimativa)", "Carboidratos ou açúcar moderados (estimativa)", "Não adequado para diabéticos (estimativa)",
        "Estimativa a partir da estimativa nutricional por porção; não é aconselhamento médico. Pessoas com diabetes devem consultar um médico ou nutricionista.",
        "Leite", "Ovos", "Glúten (trigo, cevada, centeio, aveia)", "Frutos de casca rija", "Amendoim", "Gergelim", "Soja", "Peixe", "Crustáceos", "Moluscos", "Aipo", "Mostarda", "Tremoço", "Sulfitos"),
 'ja': ("含む", "主要なアレルゲンは見つかりませんでした", "アレルゲンは見つかりませんでした。市販の材料はラベルを確認してください", "アレルゲンは未評価です",
        "材料と手順から判断したもので、不完全な場合があり、保証ではありません。ラベルを確認し、コンタミネーションについても確認してください。",
        "糖尿病に適している（推定）", "炭水化物または糖質が中程度（推定）", "糖尿病には適さない（推定）",
        "1食あたりの栄養推定値にもとづく推定で、医学的助言ではありません。糖尿病の方は医師または管理栄養士にご相談ください。",
        "乳", "卵", "グルテン（小麦・大麦・ライ麦・オーツ麦）", "木の実", "落花生", "ごま", "大豆", "魚", "甲殻類", "軟体動物", "セロリ", "からし", "ルピナス", "亜硫酸塩"),
 'zh': ("含有", "未发现主要过敏原", "未发现过敏原；外购食材请查看标签", "尚未评估过敏原",
        "根据食材和步骤推断，可能不完整，也不是保证。请查看标签并询问是否存在交叉污染。",
        "适合糖尿病患者（估算）", "碳水化合物或糖含量中等（估算）", "不适合糖尿病患者（估算）",
        "根据每份营养估算得出，不是医疗建议。糖尿病患者请咨询医生或营养师。",
        "牛奶", "鸡蛋", "麸质（小麦、大麦、黑麦、燕麦）", "树坚果", "花生", "芝麻", "大豆", "鱼", "甲壳类", "软体动物", "芹菜", "芥末", "羽扇豆", "亚硫酸盐"),
 'hi': ("इसमें है", "कोई प्रमुख एलर्जन नहीं मिला", "कोई एलर्जन नहीं मिला; खरीदी गई सामग्री के लेबल जाँचें", "एलर्जन का अभी आकलन नहीं हुआ",
        "सामग्री और चरणों से निकाला गया है; अधूरा हो सकता है और गारंटी नहीं है। लेबल पढ़ें और क्रॉस-संदूषण के बारे में पूछें।",
        "मधुमेह के लिए उपयुक्त (अनुमान)", "मध्यम कार्बोहाइड्रेट या चीनी (अनुमान)", "मधुमेह के लिए उपयुक्त नहीं (अनुमान)",
        "प्रति सर्विंग पोषण अनुमान पर आधारित अनुमान है; चिकित्सकीय सलाह नहीं। मधुमेह वाले लोग डॉक्टर या आहार विशेषज्ञ से पूछें।",
        "दूध", "अंडे", "ग्लूटेन (गेहूँ, जौ, राई, जई)", "मेवे", "मूँगफली", "तिल", "सोया", "मछली", "क्रस्टेशियन", "मोलस्क", "सेलरी", "सरसों", "ल्यूपिन", "सल्फाइट"),
 'ko': ("함유", "주요 알레르기 유발 성분이 발견되지 않음", "알레르기 유발 성분이 발견되지 않음; 구입한 재료의 라벨을 확인하세요", "알레르기 성분 아직 평가되지 않음",
        "재료와 조리 단계로 판단한 것이며 불완전할 수 있고 보증이 아닙니다. 라벨을 확인하고 교차 오염에 대해 문의하세요.",
        "당뇨 친화적 (추정)", "탄수화물 또는 당 보통 (추정)", "당뇨에 적합하지 않음 (추정)",
        "1인분 영양 추정치를 바탕으로 한 추정이며 의학적 조언이 아닙니다. 당뇨가 있으신 분은 의사나 영양사와 상담하세요.",
        "우유", "달걀", "글루텐(밀, 보리, 호밀, 귀리)", "견과류", "땅콩", "참깨", "대두", "생선", "갑각류", "연체동물", "셀러리", "겨자", "루핀", "아황산염"),
 'id': ("Mengandung", "Tidak ditemukan alergen utama", "Tidak ditemukan alergen; periksa label bahan yang dibeli", "Alergen belum dinilai",
        "Disimpulkan dari bahan dan langkah; bisa tidak lengkap dan bukan jaminan. Baca label dan tanyakan soal kontaminasi silang.",
        "Ramah diabetes (perkiraan)", "Karbohidrat atau gula sedang (perkiraan)", "Tidak ramah diabetes (perkiraan)",
        "Perkiraan berdasarkan estimasi gizi per porsi; bukan nasihat medis. Penderita diabetes sebaiknya bertanya kepada dokter atau ahli gizi.",
        "Susu", "Telur", "Gluten (gandum, jelai, gandum hitam, oat)", "Kacang pohon", "Kacang tanah", "Wijen", "Kedelai", "Ikan", "Krustasea", "Moluska", "Seledri", "Biji sawi", "Lupin", "Sulfit"),
 'fa': ("شامل", "آلرژن اصلی یافت نشد", "آلرژنی یافت نشد؛ برچسب مواد خریداری‌شده را بررسی کنید", "آلرژن‌ها هنوز ارزیابی نشده‌اند",
        "از روی مواد و مراحل استنباط شده؛ ممکن است ناقص باشد و تضمین نیست. برچسب‌ها را بخوانید و درباره آلودگی متقاطع بپرسید.",
        "مناسب دیابتی‌ها (تخمینی)", "کربوهیدرات یا قند متوسط (تخمینی)", "نامناسب برای دیابتی‌ها (تخمینی)",
        "تخمینی بر پایه برآورد ارزش غذایی هر وعده؛ توصیه پزشکی نیست. افراد دیابتی از پزشک یا متخصص تغذیه بپرسند.",
        "شیر", "تخم‌مرغ", "گلوتن (گندم، جو، چاودار، جو دوسر)", "آجیل درختی", "بادام‌زمینی", "کنجد", "سویا", "ماهی", "سخت‌پوستان", "نرم‌تنان", "کرفس", "خردل", "لوپین", "سولفیت‌ها"),
 'el': ("Περιέχει", "Δεν βρέθηκαν βασικά αλλεργιογόνα", "Δεν βρέθηκαν αλλεργιογόνα· ελέγξτε τις ετικέτες των αγορασμένων υλικών", "Τα αλλεργιογόνα δεν έχουν αξιολογηθεί ακόμη",
        "Προκύπτει από τα υλικά και τα βήματα· μπορεί να είναι ελλιπές και δεν αποτελεί εγγύηση. Διαβάστε τις ετικέτες και ρωτήστε για διασταυρούμενη επιμόλυνση.",
        "Κατάλληλο για διαβητικούς (εκτίμηση)", "Μέτριοι υδατάνθρακες ή ζάχαρη (εκτίμηση)", "Ακατάλληλο για διαβητικούς (εκτίμηση)",
        "Εκτίμηση βάσει της διατροφικής εκτίμησης ανά μερίδα· δεν αποτελεί ιατρική συμβουλή. Οι άνθρωποι με διαβήτη να ρωτούν γιατρό ή διαιτολόγο.",
        "Γάλα", "Αυγά", "Γλουτένη (σιτάρι, κριθάρι, σίκαλη, βρώμη)", "Ξηροί καρποί", "Φιστίκια", "Σησάμι", "Σόγια", "Ψάρι", "Καρκινοειδή", "Μαλάκια", "Σέλινο", "Μουστάρδα", "Λούπινο", "Θειώδη"),
 'nl': ("Bevat", "Geen belangrijke allergenen gevonden", "Geen allergenen gevonden; controleer de etiketten van gekochte ingrediënten", "Allergenen nog niet beoordeeld",
        "Afgeleid uit de ingrediënten en stappen; kan onvolledig zijn en is geen garantie. Lees de etiketten en vraag naar kruisbesmetting.",
        "Geschikt voor diabetici (schatting)", "Matig koolhydraten of suiker (schatting)", "Niet geschikt voor diabetici (schatting)",
        "Schatting op basis van de geschatte voedingswaarde per portie; geen medisch advies. Mensen met diabetes kunnen het best een arts of diëtist raadplegen.",
        "Melk", "Eieren", "Gluten (tarwe, gerst, rogge, haver)", "Noten", "Pinda's", "Sesam", "Soja", "Vis", "Schaaldieren", "Weekdieren", "Selderij", "Mosterd", "Lupine", "Sulfieten"),
 'pl': ("Zawiera", "Nie znaleziono głównych alergenów", "Nie znaleziono alergenów; sprawdź etykiety kupowanych składników", "Alergeny nie zostały jeszcze ocenione",
        "Ustalone na podstawie składników i kroków; może być niepełne i nie jest gwarancją. Czytaj etykiety i pytaj o zanieczyszczenie krzyżowe.",
        "Odpowiednie dla diabetyków (szacunek)", "Umiarkowanie węglowodanów lub cukru (szacunek)", "Nieodpowiednie dla diabetyków (szacunek)",
        "Szacunek na podstawie szacunkowej wartości odżywczej na porcję; to nie porada medyczna. Osoby z cukrzycą powinny zapytać lekarza lub dietetyka.",
        "Mleko", "Jaja", "Gluten (pszenica, jęczmień, żyto, owies)", "Orzechy", "Orzeszki ziemne", "Sezam", "Soja", "Ryby", "Skorupiaki", "Mięczaki", "Seler", "Gorczyca", "Łubin", "Siarczyny"),
 'sv': ("Innehåller", "Inga huvudsakliga allergener hittades", "Inga allergener hittades; kontrollera etiketterna på köpta ingredienser", "Allergener ännu inte bedömda",
        "Utläst ur ingredienserna och stegen; kan vara ofullständigt och är ingen garanti. Läs etiketterna och fråga om korskontaminering.",
        "Lämplig vid diabetes (uppskattning)", "Måttligt med kolhydrater eller socker (uppskattning)", "Inte lämplig vid diabetes (uppskattning)",
        "Uppskattning utifrån den uppskattade näringen per portion; inte medicinsk rådgivning. Personer med diabetes bör fråga läkare eller dietist.",
        "Mjölk", "Ägg", "Gluten (vete, korn, råg, havre)", "Nötter", "Jordnötter", "Sesam", "Soja", "Fisk", "Kräftdjur", "Blötdjur", "Selleri", "Senap", "Lupin", "Sulfiter"),
 'ur': ("شامل", "کوئی بڑا الرجن نہیں ملا", "کوئی الرجن نہیں ملا؛ خریدے ہوئے اجزا کے لیبل دیکھ لیں", "الرجن کا ابھی جائزہ نہیں لیا گیا",
        "اجزا اور مراحل سے اخذ کیا گیا ہے؛ نامکمل ہو سکتا ہے اور ضمانت نہیں ہے۔ لیبل پڑھیں اور باہمی آلودگی کے بارے میں پوچھیں۔",
        "ذیابیطس کے لیے موزوں (اندازہ)", "درمیانی کاربوہائیڈریٹ یا چینی (اندازہ)", "ذیابیطس کے لیے موزوں نہیں (اندازہ)",
        "فی حصہ غذائی اندازے پر مبنی اندازہ؛ طبی مشورہ نہیں۔ ذیابیطس کے مریض ڈاکٹر یا ماہرِ غذائیت سے پوچھیں۔",
        "دودھ", "انڈے", "گلوٹین (گندم، جو، رائی، جئی)", "گری دار میوے", "مونگ پھلی", "تل", "سویا", "مچھلی", "سخت خول والے آبی جانور", "نرم جسم والے جانور", "اجوائن", "سرسوں", "لوپین", "سلفائٹس"),
 'ku': ("Tê de heye", "Alerjenên sereke nehatin dîtin", "Alerjen nehatin dîtin; etîketên pêkhateyên kirrî kontrol bikin", "Alerjen hê nehatine nirxandin",
        "Ji pêkhate û gavan hatiye derxistin; dibe ku netemam be û ne garantî ye. Etîketan bixwînin û ji bo qirêjiya xaçerê bipirsin.",
        "Ji bo şekirê guncaw e (texmîn)", "Karbohîdrat an şekir navîn (texmîn)", "Ji bo şekirê ne guncaw e (texmîn)",
        "Texmîn li ser texmîna xwarinê ya ji bo her parçeyekê ye; ne şîreta bijîşkî ye. Kesên bi şekir divê ji bijîşk an parêzvanekî bipirsin.",
        "Şîr", "Hêk", "Gluten (genim, ceh, çavdar, yulaf)", "Fêkiyên hişk", "Fistiqa erdê", "Kuncî", "Soya", "Masî", "Qalikdarên avî", "Nermikên avî", "Karafs", "Xerdel", "Lupîn", "Sulfît"),
 'sw': ("Ina", "Hakuna vizio vikuu vilivyopatikana", "Hakuna vizio vilivyopatikana; angalia lebo za viungo vilivyonunuliwa", "Vizio bado havijakaguliwa",
        "Imetokana na viungo na hatua; inaweza kuwa pungufu na si hakikisho. Soma lebo na uulize kuhusu uchafuzi mtambuka.",
        "Inafaa kwa wenye kisukari (makadirio)", "Wanga au sukari wastani (makadirio)", "Haifai kwa wenye kisukari (makadirio)",
        "Makadirio kutokana na makadirio ya lishe kwa kila sehemu; si ushauri wa kitabibu. Wenye kisukari wamwulize daktari au mtaalamu wa lishe.",
        "Maziwa", "Mayai", "Gluteni (ngano, shayiri, rai, oti)", "Karanga za miti", "Karanga", "Ufuta", "Soya", "Samaki", "Kaa na kamba", "Moluska", "Selari", "Haradali", "Lupini", "Salfaiti"),
 'ps': ("لري", "اصلي الرژن ونه موندل شو", "هیڅ الرژن ونه موندل شو؛ د پیرل شویو توکو لیبلونه وګورئ", "الرژنونه لا نه دي ارزول شوي",
        "له توکو او ګامونو څخه اټکل شوی؛ ممکن ناقص وي او تضمین نه دی. لیبلونه ولولئ او د متقاطع ککړتیا په اړه وپوښتئ.",
        "د ډیابېټس لپاره مناسب (اټکل)", "منځنی کاربوهایدریټ یا بوره (اټکل)", "د ډیابېټس لپاره مناسب نه دی (اټکل)",
        "د هر برخې د تغذیې اټکل پر بنسټ اټکل دی؛ طبي مشوره نه ده. د ډیابېټس ناروغان له ډاکټر یا د تغذیې متخصص څخه وپوښتي.",
        "شیدې", "هګۍ", "ګلوټین (غنم، اوربشې او نور غله)", "مغزونه", "مونګ‌پلی", "کنجد", "سویا", "کب", "سخت‌پوستان", "نرم‌تنان", "کرفس", "خردل", "لوپین", "سلفایټونه"),
 'he': ("מכיל", "לא נמצאו אלרגנים עיקריים", "לא נמצאו אלרגנים; בדקו את התוויות של מרכיבים קנויים", "אלרגנים טרם הוערכו",
        "נקבע לפי המרכיבים והשלבים; ייתכן שאינו שלם ואינו הבטחה. קראו תוויות ושאלו על זיהום צולב.",
        "מתאים לחולי סוכרת (הערכה)", "פחמימות או סוכר בינוניים (הערכה)", "אינו מתאים לחולי סוכרת (הערכה)",
        "הערכה המבוססת על הערכת הערכים התזונתיים למנה; אינה ייעוץ רפואי. חולי סוכרת מתבקשים להתייעץ עם רופא או דיאטן.",
        "חלב", "ביצים", "גלוטן (חיטה, שעורה, שיפון, שיבולת שועל)", "אגוזי עץ", "בוטנים", "שומשום", "סויה", "דגים", "סרטנאים", "רכיכות", "סלרי", "חרדל", "תורמוס", "סולפיטים"),
 'te': ("కలిగి ఉంది", "ప్రధాన అలెర్జెన్లు కనబడలేదు", "అలెర్జెన్లు కనబడలేదు; కొన్న పదార్థాల లేబుల్స్ చూడండి", "అలెర్జెన్లను ఇంకా అంచనా వేయలేదు",
        "పదార్థాలు, దశల ఆధారంగా నిర్ధారించబడింది; అసంపూర్ణంగా ఉండవచ్చు, హామీ కాదు. లేబుల్స్ చదవండి, క్రాస్-కాంటాక్ట్ గురించి అడగండి.",
        "మధుమేహులకు అనుకూలం (అంచనా)", "మధ్యస్థ కార్బోహైడ్రేట్లు లేదా చక్కెర (అంచనా)", "మధుమేహులకు అనుకూలం కాదు (అంచనా)",
        "ప్రతి వడ్డనకు పోషక అంచనా ఆధారంగా చేసిన అంచనా; వైద్య సలహా కాదు. మధుమేహం ఉన్నవారు వైద్యుడిని లేదా డైటీషియన్‌ను అడగాలి.",
        "పాలు", "గుడ్లు", "గ్లూటెన్ (గోధుమ, బార్లీ, రై, ఓట్స్)", "చెట్టు గింజలు", "వేరుశనగ", "నువ్వులు", "సోయా", "చేప", "క్రస్టేషియన్లు", "మొలస్కులు", "సెలెరీ", "ఆవాలు", "లుపిన్", "సల్ఫైట్లు"),
 'bn': ("রয়েছে", "প্রধান অ্যালার্জেন পাওয়া যায়নি", "কোনো অ্যালার্জেন পাওয়া যায়নি; কেনা উপকরণের লেবেল দেখুন", "অ্যালার্জেন এখনো মূল্যায়ন করা হয়নি",
        "উপকরণ ও ধাপ থেকে নির্ণয় করা; অসম্পূর্ণ হতে পারে এবং নিশ্চয়তা নয়। লেবেল পড়ুন এবং ক্রস-কন্টাক্ট সম্পর্কে জিজ্ঞাসা করুন।",
        "ডায়াবেটিসের জন্য উপযোগী (আনুমানিক)", "মাঝারি কার্বোহাইড্রেট বা চিনি (আনুমানিক)", "ডায়াবেটিসের জন্য উপযোগী নয় (আনুমানিক)",
        "প্রতি পরিবেশনের পুষ্টি অনুমানের ভিত্তিতে আনুমানিক; চিকিৎসা পরামর্শ নয়। ডায়াবেটিস থাকলে চিকিৎসক বা পুষ্টিবিদকে জিজ্ঞাসা করুন।",
        "দুধ", "ডিম", "গ্লুটেন (গম, বার্লি, রাই, ওটস)", "গাছের বাদাম", "চিনাবাদাম", "তিল", "সয়া", "মাছ", "ক্রাস্টেসিয়ান", "মোলাস্ক", "সেলেরি", "সরিষা", "লুপিন", "সালফাইট"),
 'vi': ("Có chứa", "Không tìm thấy chất gây dị ứng chính", "Không tìm thấy chất gây dị ứng; hãy kiểm tra nhãn nguyên liệu mua sẵn", "Chưa đánh giá chất gây dị ứng",
        "Suy ra từ nguyên liệu và các bước; có thể chưa đầy đủ và không phải là bảo đảm. Hãy đọc nhãn và hỏi về nhiễm chéo.",
        "Phù hợp với người tiểu đường (ước tính)", "Tinh bột hoặc đường ở mức vừa (ước tính)", "Không phù hợp với người tiểu đường (ước tính)",
        "Ước tính dựa trên giá trị dinh dưỡng ước tính mỗi khẩu phần; không phải lời khuyên y tế. Người bị tiểu đường nên hỏi bác sĩ hoặc chuyên gia dinh dưỡng.",
        "Sữa", "Trứng", "Gluten (lúa mì, lúa mạch, lúa mạch đen, yến mạch)", "Hạt cây", "Đậu phộng", "Mè", "Đậu nành", "Cá", "Giáp xác", "Động vật thân mềm", "Cần tây", "Mù tạt", "Đậu lupin", "Sunfit"),
 'sq': ("Përmban", "Nuk u gjetën alergjenë kryesorë", "Nuk u gjetën alergjenë; kontrolloni etiketat e përbërësve të blerë", "Alergjenët ende nuk janë vlerësuar",
        "Nxjerrë nga përbërësit dhe hapat; mund të jetë e paplotë dhe nuk është garanci. Lexoni etiketat dhe pyesni për ndotjen e kryqëzuar.",
        "I përshtatshëm për diabetikët (vlerësim)", "Karbohidrate ose sheqer mesatar (vlerësim)", "Jo i përshtatshëm për diabetikët (vlerësim)",
        "Vlerësim bazuar në vlerësimin ushqyes për porcion; nuk është këshillë mjekësore. Personat me diabet të pyesin mjekun ose dietologun.",
        "Qumësht", "Vezë", "Gluten (grurë, elb, thekër, tërshërë)", "Fruta me lëvozhgë", "Kikirikë", "Susam", "Sojë", "Peshk", "Krustace", "Molusqe", "Selino", "Mustardë", "Lupinë", "Sulfite"),
 'cs': ("Obsahuje", "Nenalezeny hlavní alergeny", "Nenalezeny žádné alergeny; zkontrolujte etikety nakoupených surovin", "Alergeny zatím nebyly posouzeny",
        "Odvozeno ze surovin a kroků; může být neúplné a není zárukou. Čtěte etikety a ptejte se na křížovou kontaminaci.",
        "Vhodné pro diabetiky (odhad)", "Střední množství sacharidů nebo cukru (odhad)", "Nevhodné pro diabetiky (odhad)",
        "Odhad podle odhadované nutriční hodnoty na porci; není to lékařská rada. Lidé s cukrovkou by se měli zeptat lékaře nebo dietologa.",
        "Mléko", "Vejce", "Lepek (pšenice, ječmen, žito, oves)", "Skořápkové plody", "Arašídy", "Sezam", "Sója", "Ryby", "Korýši", "Měkkýši", "Celer", "Hořčice", "Vlčí bob", "Siřičitany"),
}
