import type { DatabaseStats, Recipe, RecipeSummary, SupportedLanguage } from '../types';
import type { GlobalIngredientSummary } from '../data/recipes';
import type { RecipeEstimate } from '../data/recipeEstimates';
import { registerRecipeEstimate } from '../data/recipeEstimates';
import { registerTranslations, type RecipeTranslation, type TranslationTable } from '../utils/recipeLocalization';

// Client for the static recipe data generated by scripts/generate-public-index.ts.
// Every request carries the data version, so browsers can cache the files
// indefinitely between deploys and still never mix old and new data.

declare const __DATA_VERSION__: string;

export interface DataManifest {
  version: string;
  pageSize: number;
  pageCount: number;
  total: number;
  stats: { all: DatabaseStats; translated: DatabaseStats };
}

export type IngredientRegistryItem = GlobalIngredientSummary & { localizedName: string };

const DATA_URL = `${import.meta.env.BASE_URL}data/`;

const inFlight = new Map<string, Promise<unknown>>();

function fetchJson<T>(path: string): Promise<T> {
  let request = inFlight.get(path) as Promise<T> | undefined;
  if (!request) {
    request = fetch(`${DATA_URL}${path}?v=${__DATA_VERSION__}`).then(response => {
      if (!response.ok) throw new Error(`${response.status} loading ${path}`);
      return response.json() as Promise<T>;
    });
    // Forget failures so a later call (e.g. after reconnecting) retries.
    request.catch(() => inFlight.delete(path));
    inFlight.set(path, request);
  }
  return request;
}

export const loadManifest = () => fetchJson<DataManifest>('manifest.json');

/**
 * Streams the card index page by page: the first page is delivered as soon as
 * it arrives, the rest follow one after another in the background so they
 * never compete with images and user actions on slow connections.
 */
export async function loadRecipeIndex(
  onPage: (recipes: RecipeSummary[], done: boolean) => void,
  isCancelled: () => boolean
): Promise<void> {
  const manifest = await loadManifest();
  for (let page = 0; page < manifest.pageCount; page++) {
    const recipes = await fetchJson<RecipeSummary[]>(`index/${page}.json`);
    if (isCancelled()) return;
    onPage(recipes, page === manifest.pageCount - 1);
  }
}

export const loadCardTranslations = (lang: SupportedLanguage) => fetchJson<TranslationTable>(`i18n/${lang}.json`);

export const loadSearchIndex = (lang: SupportedLanguage) => fetchJson<Record<string, string>>(`search/${lang}.json`);

export const loadIngredientRegistry = (lang: SupportedLanguage) => fetchJson<IngredientRegistryItem[]>(`ingredients/${lang}.json`);

interface RecipeFile {
  recipe: Recipe;
  estimate?: RecipeEstimate;
  translations: Partial<Record<SupportedLanguage, RecipeTranslation>>;
}

/** Fetches a full recipe and registers its estimate and translations. */
export async function loadRecipe(id: string): Promise<Recipe> {
  const file = await fetchJson<RecipeFile>(`recipes/${encodeURIComponent(id)}.json`);
  registerRecipeEstimate(id, file.estimate);
  for (const [lang, translation] of Object.entries(file.translations) as [SupportedLanguage, RecipeTranslation][]) {
    registerTranslations(lang, { [id]: translation });
  }
  return file.recipe;
}

/** Warms the cache for a recipe the visitor is likely to open (hover/focus). */
export function prefetchRecipe(id: string): void {
  void loadRecipe(id).catch(() => undefined);
}
