import { MasterIngredient, Recipe, UniqueInstruction } from '../../types';

// World Cuisines encyclopedia: one chapter per country, recipes distilled by
// the local pipeline (scripts/world) from real fetched sources, rewritten in
// our own words, halal-gated, and shipped only once complete (banner, thumb,
// translations, nutrition + cost). Country JSON files live in src/data/world/
// and use the compact authoring format expanded below, mirroring
// fatmaAbuHaty.ts. `ready` gates visibility: incomplete entries never list.

export interface WorldRecipe {
  id: string;                 // w-<iso2>-NNN
  title: string;              // Arabic
  titleEn: string;
  chapter: string;            // مطبخ <الدولة>
  chapterNumber: number;      // 10 + country order from world/countries.yaml
  category: string;
  method: string;
  prep?: string;
  cook?: string;
  servings?: string;
  difficulty?: Recipe['difficulty'];
  ingredients: [string, string, MasterIngredient['category'],
                string?, string?][]; // nameAr, amountAr, cat, nameEn?, amountEn?
  steps: ([string, string] | [string, string, UniqueInstruction['phase']])[];
  notes?: string;             // cultural notes, Arabic
  notesEn?: string;
  sourceName: string;
  sourceUrl: string;
  imageBrief?: string;
  /** Set false to keep the recipe in the data file but off the site. */
  ready?: boolean;
}

// Static import — src/data/world/index.ts is regenerated by
// scripts/world/import.py whenever a country file lands. (import.meta.glob
// would also work in Vite but breaks the Node-side data scripts.)
import worldEntries from '../world/index';

function toRecipe(entry: WorldRecipe): Recipe {
  const instructions: UniqueInstruction[] = entry.steps.map((step, index) => {
    const [text, textEn, phase] = step;
    return {
      stepNumber: index + 1,
      text,
      textEn,
      phase: phase ?? 'cook',
      sourceDocs: [],
      importance: 'core' as const
    };
  });
  return {
    id: entry.id,
    title: entry.title,
    titleEn: entry.titleEn,
    chapter: entry.chapter,
    chapterNumber: entry.chapterNumber,
    category: entry.category,
    cookingMethod: entry.method,
    prepTime: entry.prep,
    cookTime: entry.cook,
    servings: entry.servings,
    difficulty: entry.difficulty,
    masterIngredients: entry.ingredients.map(
      ([name, standardAmount, category, nameEn, standardAmountEn], index) => ({
        id: `${entry.id}-i${index + 1}`,
        name,
        nameEn,
        standardAmount,
        standardAmountEn,
        category,
        sourceVariations: {},
        isMerged: false,
        originalOccurrencesCount: 1
      })),
    uniqueInstructions: instructions,
    culturalNotes: entry.notes,
    source: {
      name: entry.sourceName,
      url: entry.sourceUrl,
      collection: 'world'
    },
    overlapAnalysis: {
      duplicateInstructionCount: 0,
      mergedIngredientsCount: 0,
      totalUniqueSteps: instructions.length,
      totalMasterIngredients: entry.ingredients.length,
      overlapPercentage: 0,
      documentsPresent: [],
      reconciliationSummary:
        'وصفة من مطابخ العالم، أعدنا صياغتها بأسلوبنا مع حفظ حق المصدر. تفترض الوصفة استخدام لحوم مذكاة حلال.'
    },
    rawDocVersions: {}
  };
}

const entries = worldEntries as unknown as WorldRecipe[];

/** Every world entry as a Recipe, including not-yet-ready ones — for tooling
 * (banner export, translation drafts). Never rendered. */
export const allWorldRecipes: Recipe[] = entries.map(toRecipe);

/** Only fully-complete recipes are listed on the site. */
export const worldRecipes: Recipe[] = entries
  .filter(e => e.ready === true)
  .map(toRecipe);
