// Cloudflare Worker routed ONLY on fifi.cooking/data/tv/feed/*.
//
// Same URL, same response shape as the static file it replaces
// ({ rows: [{ key, title, items }] }) — clients need no change. Behind the
// URL it picks a random pre-built home layout from the static
// /data/tv/feed-variants/{lang}.json (generated by scripts/generate-tv-index.ts)
// on every request. The layout's hero becomes the first "featured" item, which
// is what every client shows as the hero.
//
// Any failure falls through to the original static feed, so the apps keep
// working if the variants file is missing.

const FEED_PATH = /^\/data\/tv\/feed\/([a-z]{2,3})\.json$/;
const FEATURED_SIZE = 20;

const pick = (items) => items[Math.floor(Math.random() * items.length)];

export function layoutFrom(variants) {
  const { hero, rows } = pick(variants);
  return {
    rows: rows.map((row) =>
      row.key === 'featured'
        ? { ...row, items: [hero, ...row.items.filter((id) => id !== hero)].slice(0, FEATURED_SIZE) }
        : row
    )
  };
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const match = request.method === 'GET' && FEED_PATH.exec(url.pathname);
    if (!match) return fetch(request);
    try {
      // Same-zone subrequest goes to the origin (GitHub Pages), not back into this Worker.
      const source = await fetch(new URL(`/data/tv/feed-variants/${match[1]}.json`, url), {
        cf: { cacheTtl: 600, cacheEverything: true }
      });
      if (!source.ok) return fetch(request);
      const { variants } = await source.json();
      if (!Array.isArray(variants) || variants.length === 0) return fetch(request);
      return new Response(JSON.stringify(layoutFrom(variants)), {
        headers: {
          'content-type': 'application/json; charset=utf-8',
          'access-control-allow-origin': '*',
          // Every request must reach the Worker: that is what makes it random.
          'cache-control': 'no-store'
        }
      });
    } catch {
      return fetch(request);
    }
  }
};
