// Generated by scripts/world/import.py — do not edit by hand.
import w_cn from './cn.json';
import w_es from './es.json';
import w_fr from './fr.json';
import w_id from './id.json';
import w_in from './in.json';
import w_it from './it.json';
import w_jp from './jp.json';
import w_kr from './kr.json';
import w_ma from './ma.json';
import w_mx from './mx.json';
import w_th from './th.json';
import w_tr from './tr.json';
import w_vn from './vn.json';

const worldEntries = [...w_cn, ...w_es, ...w_fr, ...w_id, ...w_in, ...w_it, ...w_jp, ...w_kr, ...w_ma, ...w_mx, ...w_th, ...w_tr, ...w_vn];
export default worldEntries;
