// Generated by scripts/world/import.py — do not edit by hand.
import jp from './jp.json';
import ma from './ma.json';
import mx from './mx.json';

const worldEntries = [...jp, ...ma, ...mx];
export default worldEntries;
