import type { RecipeEstimate } from './recipeEstimates';

// Estimated nutrition (per serving) and ingredient cost (whole
// recipe, USD) for world-cuisine recipes; same approximation rules
// as recipeEstimates.ts. Generated by scripts/world/estimates.py.
export const WORLD_RECIPE_ESTIMATES: Record<string, RecipeEstimate> = {
  "w-cn-001": {
    "servings": 5,
    "kcal": 390,
    "protein": 13,
    "fat": 2,
    "carbs": 80,
    "fiber": 3,
    "sugar": 1,
    "cost": {
      "grains": 1.2,
      "specialty": 0.8,
      "spices": 0.1
    }
  },
  "w-cn-002": {
    "servings": 14,
    "kcal": 210,
    "protein": 9,
    "fat": 7,
    "carbs": 27,
    "fiber": 1,
    "sugar": 1,
    "cost": {
      "protein": 7,
      "grains": 0.8,
      "produce": 0.5,
      "fats": 0.4,
      "dairyEggs": 0.3,
      "spices": 0.4
    }
  },
  "w-cn-003": {
    "servings": 5,
    "kcal": 90,
    "protein": 3,
    "fat": 7,
    "carbs": 6,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "produce": 3,
      "fats": 0.8,
      "specialty": 0.6,
      "spices": 0.4
    }
  },
  "w-cn-004": {
    "servings": 5,
    "kcal": 380,
    "protein": 22,
    "fat": 9,
    "carbs": 52,
    "fiber": 3,
    "sugar": 6,
    "cost": {
      "protein": 6,
      "grains": 3,
      "produce": 2.5,
      "specialty": 0.8,
      "fats": 0.4,
      "spices": 0.3
    }
  },
  "w-cn-005": {
    "servings": 5,
    "kcal": 140,
    "protein": 5,
    "fat": 4,
    "carbs": 22,
    "fiber": 4,
    "sugar": 4,
    "cost": {
      "specialty": 6,
      "grains": 1,
      "produce": 1,
      "fats": 0.5,
      "spices": 0.3
    }
  },
  "w-cn-006": {
    "servings": 5,
    "kcal": 120,
    "protein": 9,
    "fat": 7,
    "carbs": 5,
    "fiber": 1,
    "sugar": 1,
    "cost": {
      "protein": 4.5,
      "specialty": 0.8,
      "fats": 0.3
    }
  },
  "w-cn-007": {
    "servings": 5,
    "kcal": 240,
    "protein": 17,
    "fat": 15,
    "carbs": 10,
    "fiber": 1,
    "sugar": 6,
    "cost": {
      "protein": 5,
      "dairyEggs": 1.8,
      "produce": 1.2,
      "specialty": 0.8,
      "sweeteners": 0.3
    }
  },
  "w-cn-008": {
    "servings": 7,
    "kcal": 290,
    "protein": 6,
    "fat": 15,
    "carbs": 33,
    "fiber": 1,
    "sugar": 15,
    "cost": {
      "dairyEggs": 3.5,
      "grains": 0.8,
      "sweeteners": 0.8,
      "fats": 0.3
    }
  },
  "w-cn-009": {
    "servings": 5,
    "kcal": 300,
    "protein": 5,
    "fat": 8,
    "carbs": 54,
    "fiber": 2,
    "sugar": 18,
    "cost": {
      "grains": 1,
      "specialty": 1.5,
      "sweeteners": 0.8,
      "spices": 0.2
    }
  },
  "w-cn-010": {
    "servings": 5,
    "kcal": 480,
    "protein": 32,
    "fat": 22,
    "carbs": 38,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "protein": 8,
      "grains": 1.2,
      "produce": 1,
      "specialty": 1,
      "fats": 0.8,
      "spices": 0.4
    }
  },
  "w-cn-011": {
    "servings": 5,
    "kcal": 120,
    "protein": 4,
    "fat": 10,
    "carbs": 5,
    "fiber": 1,
    "sugar": 2,
    "cost": {
      "specialty": 3.5,
      "produce": 0.5,
      "fats": 0.5,
      "spices": 0.2
    }
  },
  "w-cn-012": {
    "servings": 5,
    "kcal": 280,
    "protein": 20,
    "fat": 16,
    "carbs": 15,
    "fiber": 2,
    "sugar": 10,
    "cost": {
      "protein": 4,
      "specialty": 1.5,
      "produce": 1.5,
      "fats": 0.5,
      "sweeteners": 0.4,
      "spices": 0.4
    }
  },
  "w-cn-013": {
    "servings": 5,
    "kcal": 320,
    "protein": 3,
    "fat": 1,
    "carbs": 76,
    "fiber": 4,
    "sugar": 40,
    "cost": {
      "produce": 3,
      "sweeteners": 3,
      "grains": 0.6
    }
  },
  "w-cn-014": {
    "servings": 7,
    "kcal": 160,
    "protein": 5,
    "fat": 1,
    "carbs": 33,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "grains": 0.7,
      "sweeteners": 0.15,
      "specialty": 0.2
    }
  },
  "w-cn-015": {
    "servings": 5,
    "kcal": 200,
    "protein": 13,
    "fat": 11,
    "carbs": 12,
    "fiber": 0,
    "sugar": 5,
    "cost": {
      "protein": 6,
      "dairyEggs": 0.9,
      "specialty": 0.6,
      "grains": 0.3,
      "sweeteners": 0.2
    }
  },
  "w-cn-016": {
    "servings": 5,
    "kcal": 260,
    "protein": 9,
    "fat": 1,
    "carbs": 53,
    "fiber": 0,
    "sugar": 1,
    "cost": {
      "protein": 4,
      "grains": 2,
      "spices": 0.1
    }
  },
  "w-cn-017": {
    "servings": 5,
    "kcal": 340,
    "protein": 6,
    "fat": 3,
    "carbs": 72,
    "fiber": 4,
    "sugar": 25,
    "cost": {
      "specialty": 2.5,
      "grains": 1.5,
      "fats": 0.3
    }
  },
  "w-cn-018": {
    "servings": 5,
    "kcal": 100,
    "protein": 7,
    "fat": 5,
    "carbs": 5,
    "fiber": 0,
    "sugar": 4,
    "cost": {
      "dairyEggs": 3,
      "specialty": 0.8,
      "spices": 0.4,
      "sweeteners": 0.2
    }
  },
  "w-cn-019": {
    "servings": 5,
    "kcal": 310,
    "protein": 26,
    "fat": 15,
    "carbs": 18,
    "fiber": 2,
    "sugar": 7,
    "cost": {
      "protein": 5,
      "specialty": 2,
      "grains": 1,
      "produce": 1,
      "fats": 0.4,
      "sweeteners": 0.4,
      "spices": 0.3
    }
  },
  "w-cn-020": {
    "servings": 5,
    "kcal": 220,
    "protein": 6,
    "fat": 9,
    "carbs": 30,
    "fiber": 1,
    "sugar": 1,
    "cost": {
      "grains": 0.6,
      "fats": 1.2,
      "dairyEggs": 0.3
    }
  },
  "w-cn-021": {
    "servings": 25,
    "kcal": 120,
    "protein": 3,
    "fat": 1,
    "carbs": 27,
    "fiber": 1,
    "sugar": 8,
    "cost": {
      "specialty": 2.5,
      "grains": 1.5
    }
  },
  "w-fr-001": {
    "servings": 7,
    "kcal": 420,
    "protein": 48,
    "fat": 14,
    "carbs": 22,
    "fiber": 3,
    "sugar": 5,
    "cost": {
      "protein": 42,
      "produce": 8,
      "fats": 6,
      "spices": 1.5
    }
  },
  "w-fr-002": {
    "servings": 5,
    "kcal": 380,
    "protein": 24,
    "fat": 18,
    "carbs": 28,
    "fiber": 1,
    "sugar": 4,
    "cost": {
      "protein": 9,
      "dairyEggs": 1.5,
      "produce": 1.5,
      "grains": 0.4,
      "fats": 1.5,
      "spices": 0.3
    }
  },
  "w-fr-003": {
    "servings": 14,
    "kcal": 150,
    "protein": 3,
    "fat": 6,
    "carbs": 23,
    "fiber": 1,
    "sugar": 18,
    "cost": {
      "specialty": 5,
      "sweeteners": 4.5,
      "grains": 0.4,
      "dairyEggs": 0.25,
      "spices": 0.3
    }
  },
  "w-fr-004": {
    "servings": 5,
    "kcal": 190,
    "protein": 1,
    "fat": 19,
    "carbs": 6,
    "fiber": 0,
    "sugar": 0,
    "cost": {
      "produce": 1.5,
      "fats": 4.5,
      "spices": 0.3
    }
  },
  "w-fr-005": {
    "servings": 4,
    "kcal": 640,
    "protein": 38,
    "fat": 48,
    "carbs": 1,
    "fiber": 0,
    "sugar": 0,
    "cost": {
      "protein": 14,
      "fats": 9,
      "produce": 0.8,
      "spices": 1.5
    }
  },
  "w-fr-006": {
    "servings": 5,
    "kcal": 520,
    "protein": 9,
    "fat": 30,
    "carbs": 55,
    "fiber": 4,
    "sugar": 6,
    "cost": {
      "produce": 4,
      "dairyEggs": 7.5,
      "grains": 0.7,
      "spices": 0.3
    }
  },
  "w-fr-007": {
    "servings": 5,
    "kcal": 380,
    "protein": 5,
    "fat": 16,
    "carbs": 55,
    "fiber": 6,
    "sugar": 3,
    "cost": {
      "produce": 3,
      "dairyEggs": 0.8,
      "fats": 0.5,
      "spices": 0.4
    }
  },
  "w-fr-008": {
    "servings": 5,
    "kcal": 260,
    "protein": 7,
    "fat": 11,
    "carbs": 34,
    "fiber": 2,
    "sugar": 8,
    "cost": {
      "grains": 0.4,
      "dairyEggs": 1.8,
      "sweeteners": 0.5,
      "specialty": 0.8,
      "spices": 0.1
    }
  },
  "w-fr-009": {
    "servings": 22,
    "kcal": 160,
    "protein": 2,
    "fat": 11,
    "carbs": 13,
    "fiber": 1,
    "sugar": 9,
    "cost": {
      "specialty": 7,
      "dairyEggs": 1.6,
      "sweeteners": 0.6
    }
  },
  "w-fr-010": {
    "servings": 5,
    "kcal": 330,
    "protein": 7,
    "fat": 18,
    "carbs": 36,
    "fiber": 4,
    "sugar": 5,
    "cost": {
      "produce": 2,
      "dairyEggs": 3,
      "fats": 0.3,
      "spices": 0.3
    }
  },
  "w-fr-011": {
    "servings": 5,
    "kcal": 480,
    "protein": 5,
    "fat": 16,
    "carbs": 82,
    "fiber": 3,
    "sugar": 48,
    "cost": {
      "sweeteners": 4.5,
      "grains": 1.2,
      "dairyEggs": 1.6,
      "spices": 1.2,
      "specialty": 2
    }
  },
  "w-fr-012": {
    "servings": 5,
    "kcal": 420,
    "protein": 8,
    "fat": 24,
    "carbs": 45,
    "fiber": 4,
    "sugar": 9,
    "cost": {
      "produce": 3,
      "dairyEggs": 3.5,
      "protein": 3,
      "specialty": 2.5,
      "grains": 0.5,
      "spices": 0.4
    }
  },
  "w-fr-013": {
    "servings": 5,
    "kcal": 140,
    "protein": 3,
    "fat": 10,
    "carbs": 14,
    "fiber": 6,
    "sugar": 8,
    "cost": {
      "produce": 7,
      "fats": 2,
      "spices": 0.4
    }
  },
  "w-fr-014": {
    "servings": 5,
    "kcal": 320,
    "protein": 14,
    "fat": 20,
    "carbs": 25,
    "fiber": 5,
    "sugar": 4,
    "cost": {
      "produce": 6,
      "protein": 4,
      "fats": 2.5,
      "specialty": 2
    }
  },
  "w-jp-001": {
    "servings": 10,
    "kcal": 180,
    "protein": 5,
    "fat": 5,
    "carbs": 30,
    "fiber": 1,
    "sugar": 8,
    "cost": {
      "grains": 0.45,
      "dairyEggs": 0.55,
      "sweeteners": 0.35,
      "fats": 0.4,
      "spices": 0.1
    }
  },
  "w-jp-002": {
    "servings": 6,
    "kcal": 320,
    "protein": 10,
    "fat": 14,
    "carbs": 38,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "grains": 1.2,
      "produce": 3.8,
      "dairyEggs": 0.7,
      "fats": 0.6,
      "spices": 0.3
    }
  },
  "w-jp-003": {
    "servings": 8,
    "kcal": 280,
    "protein": 10,
    "fat": 11,
    "carbs": 38,
    "fiber": 3,
    "sugar": 6,
    "cost": {
      "grains": 0.75,
      "dairyEggs": 0.6,
      "produce": 1.2,
      "fats": 0.5,
      "sweeteners": 0.15,
      "spices": 0.3,
      "specialty": 0.8
    }
  },
  "w-jp-004": {
    "servings": 12,
    "kcal": 180,
    "protein": 2,
    "fat": 1,
    "carbs": 38,
    "fiber": 1,
    "sugar": 12,
    "cost": {
      "grains": 0.75,
      "sweeteners": 0.25,
      "produce": 1.5,
      "specialty": 2.0,
      "spices": 0.1
    }
  },
  "w-jp-005": {
    "servings": 5,
    "kcal": 110,
    "protein": 4.5,
    "fat": 2.3,
    "carbs": 18.5,
    "fiber": 1.2,
    "sugar": 3.1,
    "cost": {
      "grains": 0.45,
      "produce": 0.75,
      "specialty": 0.6,
      "spices": 0.2
    }
  },
  "w-jp-006": {
    "servings": 5,
    "kcal": 12,
    "protein": 1.5,
    "fat": 0.3,
    "carbs": 1.2,
    "fiber": 0.2,
    "sugar": 0.3,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 0.35,
      "fats": 0.25
    }
  },
  "w-jp-007": {
    "servings": 5,
    "kcal": 280,
    "protein": 7,
    "fat": 8,
    "carbs": 48,
    "fiber": 2,
    "sugar": 22,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 0.8,
      "grains": 0.4,
      "sweeteners": 0.6,
      "fats": 0.3
    }
  },
  "w-jp-008": {
    "servings": 5,
    "kcal": 68,
    "protein": 0.5,
    "fat": 0.1,
    "carbs": 17.5,
    "fiber": 0.5,
    "sugar": 10.2,
    "cost": {
      "produce": 1.2,
      "grains": 0.15,
      "sweeteners": 0.3,
      "spices": 0.25
    }
  },
  "w-jp-009": {
    "servings": 6,
    "kcal": 210,
    "protein": 5,
    "fat": 12,
    "carbs": 22,
    "fiber": 0,
    "sugar": 18,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 0.75,
      "grains": 0.15,
      "fats": 0.4,
      "sweeteners": 0.1
    }
  },
  "w-jp-010": {
    "servings": 1,
    "kcal": 520,
    "protein": 22,
    "fat": 18,
    "carbs": 65,
    "fiber": 5,
    "sugar": 8,
    "cost": {
      "grains": 0.45,
      "dairyEggs": 0.6,
      "produce": 0.75,
      "fats": 0.3,
      "spices": 0.1
    }
  },
  "w-jp-011": {
    "servings": 5,
    "kcal": 520,
    "protein": 38,
    "fat": 28,
    "carbs": 42,
    "fiber": 5,
    "sugar": 8,
    "cost": {
      "protein": 4.2,
      "dairyEggs": 0.3,
      "produce": 1.8,
      "grains": 0.6,
      "fats": 0.4,
      "spices": 0.2
    }
  },
  "w-jp-012": {
    "servings": 5,
    "kcal": 320,
    "protein": 10,
    "fat": 12,
    "carbs": 42,
    "fiber": 2,
    "sugar": 18,
    "cost": {
      "dairyEggs": 1.0,
      "sweeteners": 0.8,
      "grains": 0.15,
      "specialty": 1.55,
      "fats": 0.1
    }
  },
  "w-jp-013": {
    "servings": 6,
    "kcal": 220,
    "protein": 6,
    "fat": 7,
    "carbs": 35,
    "fiber": 1,
    "sugar": 10,
    "cost": {
      "grains": 0.45,
      "dairyEggs": 0.65,
      "fats": 0.35,
      "sweeteners": 0.15,
      "spices": 0.05
    }
  },
  "w-jp-014": {
    "servings": 5,
    "kcal": 210,
    "protein": 12,
    "fat": 11,
    "carbs": 20,
    "fiber": 3,
    "sugar": 3,
    "cost": {
      "dairyEggs": 0.75,
      "produce": 1.2,
      "grains": 0.4,
      "fats": 0.6,
      "spices": 0.3,
      "specialty": 0.8
    }
  },
  "w-jp-015": {
    "servings": 5,
    "kcal": 120,
    "protein": 14,
    "fat": 6,
    "carbs": 3,
    "fiber": 0,
    "sugar": 1,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 0.8,
      "specialty": 3.5,
      "spices": 0.3
    }
  },
  "w-jp-016": {
    "servings": 5,
    "kcal": 320,
    "protein": 28,
    "fat": 18,
    "carbs": 16,
    "fiber": 3,
    "sugar": 6,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 1.8,
      "grains": 0.2,
      "fats": 0.35,
      "spices": 0.15,
      "sweeteners": 0.1
    }
  },
  "w-jp-017": {
    "servings": 5,
    "kcal": 420,
    "protein": 22,
    "fat": 24,
    "carbs": 38,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 1.8,
      "grains": 0.6,
      "fats": 0.75,
      "sweeteners": 0.3,
      "specialty": 1.5,
      "spices": 0.25
    }
  },
  "w-jp-018": {
    "servings": 5,
    "kcal": 140,
    "protein": 0,
    "fat": 0,
    "carbs": 37,
    "fiber": 0,
    "sugar": 35,
    "cost": {
      "sweeteners": 0.75,
      "specialty": 1.2
    }
  },
  "w-jp-019": {
    "servings": 12,
    "kcal": 180,
    "protein": 2.5,
    "fat": 1.2,
    "carbs": 38.5,
    "fiber": 1.1,
    "sugar": 19.8,
    "cost": {
      "sweeteners": 0.35,
      "grains": 0.45,
      "produce": 1.2,
      "spices": 0.05
    }
  },
  "w-jp-020": {
    "servings": 4,
    "kcal": 85,
    "protein": 8,
    "fat": 3,
    "carbs": 7,
    "fiber": 2,
    "sugar": 2,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 0.75,
      "grains": 0.15,
      "spices": 0.1
    }
  },
  "w-jp-021": {
    "servings": 2,
    "kcal": 320,
    "protein": 12,
    "fat": 14,
    "carbs": 38,
    "fiber": 5,
    "sugar": 8,
    "cost": {
      "grains": 1.2,
      "produce": 2.1,
      "fats": 0.9,
      "spices": 0.3,
      "specialty": 1.8,
      "sweeteners": 0.4
    }
  },
  "w-jp-022": {
    "servings": 6,
    "kcal": 52,
    "protein": 0.6,
    "fat": 1.1,
    "carbs": 10.2,
    "fiber": 1.1,
    "sugar": 6.3,
    "cost": {
      "produce": 1.25,
      "fats": 0.25,
      "sweeteners": 0.15,
      "spices": 0.1
    }
  },
  "w-jp-023": {
    "servings": 5,
    "kcal": 320,
    "protein": 12,
    "fat": 16,
    "carbs": 35,
    "fiber": 4,
    "sugar": 6,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 1.2,
      "grains": 0.75,
      "fats": 0.6,
      "spices": 0.3,
      "specialty": 1.1
    }
  },
  "w-jp-024": {
    "servings": 4,
    "kcal": 380,
    "protein": 28,
    "fat": 18,
    "carbs": 32,
    "fiber": 3,
    "sugar": 8,
    "cost": {
      "protein": 1.2,
      "dairyEggs": 0.6,
      "produce": 0.85,
      "grains": 0.3,
      "fats": 0.25,
      "sweeteners": 0.1,
      "spices": 0.1
    }
  },
  "w-jp-025": {
    "servings": 6,
    "kcal": 280,
    "protein": 12,
    "fat": 8,
    "carbs": 42,
    "fiber": 3,
    "sugar": 4,
    "cost": {
      "grains": 0.45,
      "dairyEggs": 0.6,
      "produce": 1.2,
      "fats": 0.3,
      "sweeteners": 0.1,
      "specialty": 1.5,
      "spices": 0.25
    }
  },
  "w-jp-026": {
    "servings": 4,
    "kcal": 120,
    "protein": 10,
    "fat": 6,
    "carbs": 10,
    "fiber": 2,
    "sugar": 4,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 1.5,
      "grains": 0.3,
      "spices": 0.25,
      "specialty": 1.0
    }
  },
  "w-jp-027": {
    "servings": 5,
    "kcal": 120,
    "protein": 3,
    "fat": 0.5,
    "carbs": 26,
    "fiber": 1,
    "sugar": 2,
    "cost": {
      "produce": 2.5,
      "grains": 1.2
    }
  },
  "w-jp-028": {
    "servings": 6,
    "kcal": 180,
    "protein": 5,
    "fat": 7,
    "carbs": 28,
    "fiber": 1,
    "sugar": 10,
    "cost": {
      "grains": 0.45,
      "dairyEggs": 0.35,
      "fats": 0.6,
      "sweeteners": 0.15,
      "produce": 0.2,
      "spices": 0.05
    }
  },
  "w-jp-029": {
    "servings": 5,
    "kcal": 280,
    "protein": 38,
    "fat": 16,
    "carbs": 6,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "protein": 12.5,
      "produce": 4.2,
      "spices": 1.8
    }
  },
  "w-jp-030": {
    "servings": 5,
    "kcal": 180,
    "protein": 4,
    "fat": 2,
    "carbs": 38,
    "fiber": 4,
    "sugar": 16,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 0.75,
      "grains": 0.6,
      "sweeteners": 0.3,
      "spices": 0.1
    }
  },
  "w-jp-031": {
    "servings": 5,
    "kcal": 42,
    "protein": 0.3,
    "fat": 0.1,
    "carbs": 10.5,
    "fiber": 0.5,
    "sugar": 8.2,
    "cost": {
      "sweeteners": 0.15,
      "produce": 0.75,
      "fats": 0.1,
      "spices": 0.05
    }
  },
  "w-jp-032": {
    "servings": 1,
    "kcal": 320,
    "protein": 10,
    "fat": 12,
    "carbs": 40,
    "fiber": 3,
    "sugar": 2,
    "cost": {
      "grains": 0.45,
      "fats": 0.15
    }
  },
  "w-jp-033": {
    "servings": 6,
    "kcal": 210,
    "protein": 6,
    "fat": 6,
    "carbs": 34,
    "fiber": 1,
    "sugar": 10,
    "cost": {
      "produce": 1.2,
      "grains": 0.45,
      "dairyEggs": 0.6,
      "sweeteners": 0.25,
      "spices": 0.1
    }
  },
  "w-jp-034": {
    "servings": 6,
    "kcal": 280,
    "protein": 12,
    "fat": 11,
    "carbs": 32,
    "fiber": 2,
    "sugar": 4,
    "cost": {
      "grains": 0.25,
      "dairyEggs": 0.4,
      "specialty": 7.2
    }
  },
  "w-jp-035": {
    "servings": 1,
    "kcal": 320,
    "protein": 12,
    "fat": 10,
    "carbs": 42,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "grains": 0.35,
      "dairyEggs": 0.45,
      "produce": 0.2,
      "spices": 0.15
    }
  },
  "w-jp-036": {
    "servings": 5,
    "kcal": 180,
    "protein": 10,
    "fat": 11,
    "carbs": 8,
    "fiber": 0,
    "sugar": 6,
    "cost": {
      "dairyEggs": 0.45,
      "sweeteners": 0.05,
      "spices": 0.1,
      "fats": 0.15
    }
  },
  "w-jp-037": {
    "servings": 4,
    "kcal": 280,
    "protein": 32,
    "fat": 16,
    "carbs": 6,
    "fiber": 1,
    "sugar": 2,
    "cost": {
      "dairyEggs": 0.5,
      "produce": 1.2,
      "fats": 0.4,
      "specialty": 1.8,
      "spices": 0.3
    }
  },
  "w-jp-038": {
    "servings": 5,
    "kcal": 210,
    "protein": 4,
    "fat": 12,
    "carbs": 24,
    "fiber": 3,
    "sugar": 5,
    "cost": {
      "produce": 1.8,
      "grains": 0.3,
      "fats": 0.6,
      "spices": 0.1
    }
  },
  "w-jp-039": {
    "servings": 5,
    "kcal": 280,
    "protein": 28,
    "fat": 14,
    "carbs": 18,
    "fiber": 2,
    "sugar": 8,
    "cost": {
      "protein": 2.1,
      "dairyEggs": 0.15,
      "produce": 1.8,
      "grains": 0.2,
      "fats": 0.3,
      "sweeteners": 0.1,
      "spices": 0.15
    }
  },
  "w-jp-040": {
    "servings": 5,
    "kcal": 68,
    "protein": 1.2,
    "fat": 1.1,
    "carbs": 12.3,
    "fiber": 0.3,
    "sugar": 9.1,
    "cost": {
      "specialty": 1.2,
      "sweeteners": 0.15
    }
  },
  "w-jp-042": {
    "servings": 5,
    "kcal": 120,
    "protein": 3,
    "fat": 6,
    "carbs": 14,
    "fiber": 4,
    "sugar": 3,
    "cost": {
      "grains": 1.2,
      "spices": 0.35,
      "produce": 1.8
    }
  },
  "w-jp-043": {
    "servings": 5,
    "kcal": 320,
    "protein": 18,
    "fat": 14,
    "carbs": 35,
    "fiber": 3,
    "sugar": 5,
    "cost": {
      "protein": 2.5,
      "dairyEggs": 0.3,
      "produce": 0.75,
      "grains": 0.6,
      "fats": 0.4,
      "spices": 0.25
    }
  },
  "w-jp-044": {
    "servings": 4,
    "kcal": 180,
    "protein": 4,
    "fat": 2,
    "carbs": 38,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "grains": 0.45,
      "produce": 1.2,
      "spices": 0.15,
      "specialty": 0.75
    }
  },
  "w-ma-001": {
    "servings": 6,
    "kcal": 580,
    "protein": 28,
    "fat": 42,
    "carbs": 38,
    "fiber": 5,
    "sugar": 12,
    "cost": {
      "dairyEggs": 2.4,
      "produce": 2.8,
      "grains": 1.2,
      "fats": 2.1,
      "spices": 1.5,
      "protein": 6.3
    }
  },
  "w-ma-002": {
    "servings": 6,
    "kcal": 210,
    "protein": 5,
    "fat": 18,
    "carbs": 11,
    "fiber": 4,
    "sugar": 4,
    "cost": {
      "produce": 4.2,
      "fats": 1.8,
      "spices": 0.3,
      "grains": 0.2,
      "specialty": 0.5
    }
  },
  "w-ma-003": {
    "servings": 6,
    "kcal": 180,
    "protein": 5,
    "fat": 1,
    "carbs": 38,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "grains": 1.2,
      "fats": 0.15,
      "sweeteners": 0.05,
      "spices": 0.2
    }
  },
  "w-ma-004": {
    "servings": 6,
    "kcal": 280,
    "protein": 10,
    "fat": 16,
    "carbs": 28,
    "fiber": 8,
    "sugar": 4,
    "cost": {
      "dairyEggs": 0.0,
      "produce": 1.8,
      "grains": 0.45,
      "fats": 1.2,
      "spices": 0.3,
      "specialty": 0.6
    }
  },
  "w-ma-005": {
    "servings": 5,
    "kcal": 380,
    "protein": 32,
    "fat": 26,
    "carbs": 4,
    "fiber": 0,
    "sugar": 1,
    "cost": {
      "protein": 4.2,
      "dairyEggs": 0.0,
      "produce": 0.0,
      "grains": 0.0,
      "fats": 2.8,
      "sweeteners": 0.0,
      "specialty": 1.5,
      "spices": 0.3
    }
  },
  "w-ma-006": {
    "servings": 16,
    "kcal": 380,
    "protein": 5,
    "fat": 22,
    "carbs": 45,
    "fiber": 2,
    "sugar": 32,
    "cost": {
      "specialty": 26.4,
      "fats": 2.8,
      "sweeteners": 11.75,
      "spices": 0.17,
      "dairyEggs": 3.4
    }
  },
  "w-ma-007": {
    "servings": 22,
    "kcal": 280,
    "protein": 4,
    "fat": 14,
    "carbs": 36,
    "fiber": 2,
    "sugar": 18,
    "cost": {
      "grains": 1.2,
      "fats": 2.1,
      "sweeteners": 3.5,
      "spices": 1.8,
      "produce": 1.3,
      "dairyEggs": 0.7
    }
  },
  "w-ma-008": {
    "servings": 6,
    "kcal": 210,
    "protein": 5,
    "fat": 16,
    "carbs": 14,
    "fiber": 5,
    "sugar": 5,
    "cost": {
      "produce": 3.2,
      "fats": 1.1,
      "spices": 0.75
    }
  },
  "w-ma-009": {
    "servings": 6,
    "kcal": 280,
    "protein": 4,
    "fat": 10,
    "carbs": 48,
    "fiber": 2,
    "sugar": 22,
    "cost": {
      "dairyEggs": 0.45,
      "produce": 0.75,
      "grains": 0.35,
      "fats": 0.3,
      "sweeteners": 0.25,
      "spices": 0.1
    }
  },
  "w-ma-010": {
    "servings": 22,
    "kcal": 185,
    "protein": 3.5,
    "fat": 8.2,
    "carbs": 25.1,
    "fiber": 0.6,
    "sugar": 10.3,
    "cost": {
      "dairyEggs": 1.25,
      "produce": 0.75,
      "grains": 0.45,
      "fats": 0.6,
      "sweeteners": 0.4,
      "spices": 0.15
    }
  },
  "w-ma-011": {
    "servings": 12,
    "kcal": 210,
    "protein": 4,
    "fat": 9,
    "carbs": 30,
    "fiber": 1,
    "sugar": 14,
    "cost": {
      "grains": 1.2,
      "sweeteners": 0.75,
      "dairyEggs": 1.1,
      "fats": 0.9,
      "produce": 0.6,
      "spices": 0.3
    }
  },
  "w-ma-012": {
    "servings": 8,
    "kcal": 320,
    "protein": 18,
    "fat": 14,
    "carbs": 35,
    "fiber": 8,
    "sugar": 6,
    "cost": {
      "protein": 3.2,
      "dairyEggs": 0.0,
      "produce": 4.1,
      "grains": 0.7,
      "fats": 1.1,
      "sweeteners": 0.0,
      "specialty": 0.9,
      "spices": 0.4
    }
  },
  "w-ma-013": {
    "servings": 12,
    "kcal": 680,
    "protein": 22,
    "fat": 60,
    "carbs": 18,
    "fiber": 3,
    "sugar": 2,
    "cost": {
      "dairyEggs": 0.75,
      "produce": 1.2,
      "fats": 3.5,
      "spices": 0.6,
      "grains": 0.4
    }
  },
  "w-ma-014": {
    "servings": 6,
    "kcal": 620,
    "protein": 48,
    "fat": 38,
    "carbs": 32,
    "fiber": 4,
    "sugar": 12,
    "cost": {
      "protein": 12.5,
      "dairyEggs": 0.75,
      "produce": 2.1,
      "grains": 0.4,
      "fats": 1.2,
      "sweeteners": 0.35,
      "spices": 0.2
    }
  },
  "w-ma-015": {
    "servings": 6,
    "kcal": 280,
    "protein": 4,
    "fat": 14,
    "carbs": 35,
    "fiber": 2,
    "sugar": 1,
    "cost": {
      "grains": 0.45,
      "fats": 0.3,
      "spices": 0.05
    }
  },
  "w-ma-016": {
    "servings": 6,
    "kcal": 520,
    "protein": 32,
    "fat": 38,
    "carbs": 32,
    "fiber": 5,
    "sugar": 18,
    "cost": {
      "protein": 4.2,
      "dairyEggs": 0.0,
      "produce": 2.1,
      "grains": 0.0,
      "fats": 1.8,
      "sweeteners": 0.7,
      "spices": 1.5,
      "specialty": 2.0
    }
  },
  "w-ma-017": {
    "servings": 6,
    "kcal": 320,
    "protein": 8,
    "fat": 14,
    "carbs": 42,
    "fiber": 2,
    "sugar": 4,
    "cost": {
      "grains": 1.2,
      "fats": 1.8,
      "spices": 0.3,
      "dairyEggs": 0.4
    }
  },
  "w-ma-018": {
    "servings": 6,
    "kcal": 520,
    "protein": 28,
    "fat": 32,
    "carbs": 45,
    "fiber": 4,
    "sugar": 18,
    "cost": {
      "dairyEggs": 3.2,
      "produce": 2.8,
      "grains": 1.5,
      "fats": 2.1,
      "spices": 1.7,
      "specialty": 2.4
    }
  },
  "w-ma-019": {
    "servings": 5,
    "kcal": 420,
    "protein": 38,
    "fat": 28,
    "carbs": 12,
    "fiber": 3,
    "sugar": 5,
    "cost": {
      "dairyEggs": 0.75,
      "produce": 4.2,
      "grains": 0.15,
      "fats": 1.8,
      "spices": 1.2,
      "protein": 6.5
    }
  },
  "w-ma-020": {
    "servings": 6,
    "kcal": 520,
    "protein": 38,
    "fat": 28,
    "carbs": 42,
    "fiber": 10,
    "sugar": 12,
    "cost": {
      "dairyEggs": 4.5,
      "produce": 6.2,
      "grains": 2.1,
      "fats": 3.8,
      "spices": 5.3,
      "specialty": 4.7,
      "sweeteners": 1.2
    }
  },
  "w-ma-021": {
    "servings": 6,
    "kcal": 620,
    "protein": 28,
    "fat": 38,
    "carbs": 58,
    "fiber": 4,
    "sugar": 22,
    "cost": {
      "dairyEggs": 3.2,
      "produce": 4.1,
      "grains": 1.8,
      "fats": 2.9,
      "sweeteners": 1.3,
      "spices": 1.7,
      "specialty": 2.5
    }
  },
  "w-ma-022": {
    "servings": 12,
    "kcal": 480,
    "protein": 10,
    "fat": 32,
    "carbs": 50,
    "fiber": 4,
    "sugar": 22,
    "cost": {
      "dairyEggs": 2.5,
      "produce": 3.2,
      "grains": 1.8,
      "fats": 4.1,
      "sweeteners": 1.6,
      "spices": 0.9
    }
  },
  "w-ma-023": {
    "servings": 6,
    "kcal": 280,
    "protein": 12,
    "fat": 18,
    "carbs": 22,
    "fiber": 6,
    "sugar": 10,
    "cost": {
      "produce": 4.2,
      "fats": 1.1,
      "spices": 0.3,
      "dairyEggs": 0.7
    }
  },
  "w-ma-024": {
    "servings": 6,
    "kcal": 420,
    "protein": 32,
    "fat": 24,
    "carbs": 30,
    "fiber": 5,
    "sugar": 18,
    "cost": {
      "protein": 3.2,
      "dairyEggs": 0.0,
      "produce": 2.8,
      "grains": 0.0,
      "fats": 0.7,
      "sweeteners": 0.4,
      "specialty": 1.5,
      "spices": 0.6
    }
  },
  "w-ma-025": {
    "servings": 5,
    "kcal": 520,
    "protein": 38,
    "fat": 32,
    "carbs": 24,
    "fiber": 4,
    "sugar": 6,
    "cost": {
      "dairyEggs": 3.2,
      "produce": 4.1,
      "grains": 0.75,
      "fats": 2.8,
      "spices": 1.2,
      "protein": 12.5
    }
  },
  "w-ma-026": {
    "servings": 6,
    "kcal": 120,
    "protein": 3,
    "fat": 8,
    "carbs": 12,
    "fiber": 4,
    "sugar": 6,
    "cost": {
      "produce": 4.5,
      "fats": 1.2,
      "spices": 0.75
    }
  },
  "w-ma-029": {
    "servings": 6,
    "kcal": 430,
    "protein": 31,
    "fat": 31,
    "carbs": 5,
    "fiber": 1,
    "sugar": 2,
    "cost": {
      "protein": 14.0,
      "dairyEggs": 2.1,
      "produce": 1.4,
      "fats": 0.9,
      "spices": 0.8
    }
  },
  "w-mx-001": {
    "servings": 5,
    "kcal": 120,
    "protein": 2,
    "fat": 8,
    "carbs": 10,
    "fiber": 2,
    "sugar": 5,
    "cost": {
      "produce": 3.2,
      "fats": 0.6,
      "spices": 0.4
    }
  },
  "w-mx-002": {
    "servings": 6,
    "kcal": 280,
    "protein": 32,
    "fat": 12,
    "carbs": 20,
    "fiber": 5,
    "sugar": 10,
    "cost": {
      "protein": 6.5,
      "dairyEggs": 0.0,
      "produce": 4.2,
      "grains": 0.0,
      "fats": 0.75,
      "sweeteners": 0.0,
      "specialty": 1.1,
      "spices": 0.9
    }
  },
  "w-mx-003": {
    "servings": 12,
    "kcal": 180,
    "protein": 3,
    "fat": 6,
    "carbs": 30,
    "fiber": 1,
    "sugar": 14,
    "cost": {
      "dairyEggs": 0.75,
      "produce": 0.5,
      "grains": 0.3,
      "sweeteners": 0.4,
      "spices": 0.1
    }
  },
  "w-mx-004": {
    "servings": 5,
    "kcal": 210,
    "protein": 4,
    "fat": 9,
    "carbs": 30,
    "fiber": 2,
    "sugar": 2,
    "cost": {
      "grains": 0.45,
      "produce": 1.2,
      "fats": 0.3,
      "spices": 0.15
    }
  },
  "w-mx-005": {
    "servings": 6,
    "kcal": 520,
    "protein": 42,
    "fat": 28,
    "carbs": 35,
    "fiber": 8,
    "sugar": 10,
    "cost": {
      "protein": 12.5,
      "dairyEggs": 0.0,
      "produce": 6.8,
      "grains": 1.2,
      "fats": 0.9,
      "sweeteners": 0.4,
      "spices": 1.1,
      "specialty": 2.3
    }
  },
  "w-mx-006": {
    "servings": 6,
    "kcal": 180,
    "protein": 4,
    "fat": 4,
    "carbs": 33,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "grains": 0.45,
      "sweeteners": 0.12,
      "specialty": 0.1,
      "spices": 0.02,
      "fats": 0.2
    }
  },
  "w-mx-007": {
    "servings": 6,
    "kcal": 210,
    "protein": 2.5,
    "fat": 10.5,
    "carbs": 28.5,
    "fiber": 0.5,
    "sugar": 14.5,
    "cost": {
      "sweeteners": 0.35,
      "grains": 0.15,
      "specialty": 0.65,
      "fats": 0.4,
      "spices": 0.2
    }
  },
  "w-mx-008": {
    "servings": 6,
    "kcal": 320,
    "protein": 14,
    "fat": 18,
    "carbs": 32,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "produce": 6.5,
      "dairyEggs": 3.2,
      "fats": 0.75,
      "spices": 0.4
    }
  },
  "w-mx-009": {
    "servings": 6,
    "kcal": 320,
    "protein": 32,
    "fat": 14,
    "carbs": 28,
    "fiber": 8,
    "sugar": 7,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 3.8,
      "grains": 0.4,
      "fats": 0.3,
      "spices": 0.5
    }
  },
  "w-mx-010": {
    "servings": 8,
    "kcal": 320,
    "protein": 10,
    "fat": 14,
    "carbs": 40,
    "fiber": 3,
    "sugar": 22,
    "cost": {
      "dairyEggs": 2.5,
      "produce": 1.8,
      "grains": 1.2,
      "fats": 0.9,
      "sweeteners": 1.1,
      "spices": 0.6
    }
  },
  "w-mx-011": {
    "servings": 5,
    "kcal": 320,
    "protein": 38,
    "fat": 18,
    "carbs": 6,
    "fiber": 1,
    "sugar": 2,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 3.5,
      "fats": 0.75,
      "protein": 8.0
    }
  },
  "w-mx-012": {
    "servings": 6,
    "kcal": 280,
    "protein": 8,
    "fat": 9,
    "carbs": 42,
    "fiber": 2,
    "sugar": 6,
    "cost": {
      "grains": 1.2,
      "dairyEggs": 1.1,
      "fats": 0.8,
      "spices": 0.3
    }
  },
  "w-mx-013": {
    "servings": 6,
    "kcal": 280,
    "protein": 28,
    "fat": 14,
    "carbs": 18,
    "fiber": 4,
    "sugar": 7,
    "cost": {
      "protein": 3.2,
      "produce": 4.15,
      "fats": 0.35,
      "spices": 0.2,
      "sweeteners": 0.1
    }
  },
  "w-mx-014": {
    "servings": 6,
    "kcal": 520,
    "protein": 28,
    "fat": 32,
    "carbs": 45,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "grains": 0.85,
      "dairyEggs": 1.2,
      "produce": 1.7,
      "fats": 1.4,
      "sweeteners": 0.3,
      "spices": 0.4
    }
  },
  "w-mx-015": {
    "servings": 6,
    "kcal": 180,
    "protein": 1,
    "fat": 1,
    "carbs": 42,
    "fiber": 3,
    "sugar": 32,
    "cost": {
      "spices": 0.5,
      "produce": 2.2,
      "sweeteners": 0.3,
      "specialty": 1.5
    }
  },
  "w-mx-016": {
    "servings": 5,
    "kcal": 180,
    "protein": 22,
    "fat": 8,
    "carbs": 6,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "protein": 2.5,
      "produce": 1.8,
      "spices": 0.3
    }
  },
  "w-mx-017": {
    "servings": 5,
    "kcal": 120,
    "protein": 3,
    "fat": 6,
    "carbs": 14,
    "fiber": 4,
    "sugar": 4,
    "cost": {
      "produce": 2.5,
      "spices": 0.75
    }
  },
  "w-mx-018": {
    "servings": 6,
    "kcal": 620,
    "protein": 32,
    "fat": 38,
    "carbs": 52,
    "fiber": 8,
    "sugar": 7,
    "cost": {
      "protein": 6.5,
      "dairyEggs": 1.8,
      "produce": 3.2,
      "grains": 1.1,
      "fats": 1.4,
      "spices": 0.3
    }
  },
  "w-mx-019": {
    "servings": 6,
    "kcal": 280,
    "protein": 7,
    "fat": 12,
    "carbs": 38,
    "fiber": 6,
    "sugar": 8,
    "cost": {
      "grains": 0.45,
      "produce": 3.2,
      "fats": 0.6,
      "spices": 0.35,
      "dairyEggs": 1.1,
      "specialty": 0.2
    }
  },
  "w-mx-020": {
    "servings": 6,
    "kcal": 280,
    "protein": 5,
    "fat": 10,
    "carbs": 42,
    "fiber": 1,
    "sugar": 6,
    "cost": {
      "grains": 0.45,
      "fats": 0.3,
      "sweeteners": 0.2,
      "spices": 0.1
    }
  },
  "w-mx-021": {
    "servings": 6,
    "kcal": 280,
    "protein": 22,
    "fat": 10,
    "carbs": 35,
    "fiber": 8,
    "sugar": 6,
    "cost": {
      "protein": 3.2,
      "dairyEggs": 0.0,
      "produce": 4.8,
      "grains": 1.5,
      "fats": 0.7,
      "sweeteners": 0.0,
      "specialty": 0.3,
      "spices": 0.2
    }
  },
  "w-mx-022": {
    "servings": 6,
    "kcal": 320,
    "protein": 3,
    "fat": 14,
    "carbs": 48,
    "fiber": 4,
    "sugar": 38,
    "cost": {
      "sweeteners": 0.75,
      "specialty": 2.5,
      "dairyEggs": 0.6,
      "spices": 0.35
    }
  },
  "w-mx-023": {
    "servings": 6,
    "kcal": 120,
    "protein": 2,
    "fat": 1,
    "carbs": 25,
    "fiber": 2,
    "sugar": 1,
    "cost": {
      "grains": 0.45,
      "spices": 0.05
    }
  },
  "w-mx-024": {
    "servings": 5,
    "kcal": 32,
    "protein": 1.2,
    "fat": 0.4,
    "carbs": 7.1,
    "fiber": 1.8,
    "sugar": 3.9,
    "cost": {
      "produce": 1.85,
      "fats": 0.15,
      "spices": 0.25
    }
  },
  "w-mx-025": {
    "servings": 6,
    "kcal": 380,
    "protein": 14,
    "fat": 18,
    "carbs": 42,
    "fiber": 10,
    "sugar": 5,
    "cost": {
      "produce": 4.2,
      "dairyEggs": 2.8,
      "grains": 1.5,
      "fats": 0.75,
      "spices": 0.3
    }
  },
  "w-mx-026": {
    "servings": 6,
    "kcal": 420,
    "protein": 14,
    "fat": 28,
    "carbs": 38,
    "fiber": 7,
    "sugar": 6,
    "cost": {
      "produce": 6.5,
      "dairyEggs": 3.2,
      "grains": 1.8,
      "fats": 2.1,
      "spices": 0.75
    }
  },
  "w-mx-027": {
    "servings": 6,
    "kcal": 65,
    "protein": 1,
    "fat": 1,
    "carbs": 12,
    "fiber": 2,
    "sugar": 6,
    "cost": {
      "produce": 3.2,
      "fats": 0.15,
      "spices": 0.3,
      "sweeteners": 0.1
    }
  },
  "w-mx-028": {
    "servings": 6,
    "kcal": 280,
    "protein": 8,
    "fat": 16,
    "carbs": 30,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "produce": 3.2,
      "dairyEggs": 1.8,
      "fats": 1.1,
      "spices": 0.4
    }
  },
  "w-mx-029": {
    "servings": 5,
    "kcal": 520,
    "protein": 22,
    "fat": 28,
    "carbs": 58,
    "fiber": 6,
    "sugar": 6,
    "cost": {
      "dairyEggs": 3.2,
      "produce": 4.15,
      "grains": 0.9,
      "fats": 1.1,
      "spices": 0.45
    }
  },
  "w-mx-030": {
    "servings": 5,
    "kcal": 180,
    "protein": 3,
    "fat": 14,
    "carbs": 12,
    "fiber": 7,
    "sugar": 3,
    "cost": {
      "produce": 3.2,
      "spices": 0.15
    }
  },
  "w-mx-031": {
    "servings": 8,
    "kcal": 210,
    "protein": 3,
    "fat": 2,
    "carbs": 48,
    "fiber": 2,
    "sugar": 32,
    "cost": {
      "produce": 5.5,
      "grains": 0.3,
      "sweeteners": 0.8
    }
  },
  "w-mx-032": {
    "servings": 6,
    "kcal": 520,
    "protein": 38,
    "fat": 32,
    "carbs": 38,
    "fiber": 6,
    "sugar": 4,
    "cost": {
      "protein": 3.2,
      "dairyEggs": 1.1,
      "produce": 2.8,
      "grains": 0.4,
      "fats": 1.3,
      "spices": 0.3
    }
  },
  "w-mx-033": {
    "servings": 4,
    "kcal": 420,
    "protein": 18,
    "fat": 22,
    "carbs": 45,
    "fiber": 8,
    "sugar": 6,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 2.8,
      "grains": 0.7,
      "fats": 0.6,
      "spices": 0.2,
      "specialty": 0.5
    }
  },
  "w-mx-034": {
    "servings": 6,
    "kcal": 420,
    "protein": 32,
    "fat": 24,
    "carbs": 38,
    "fiber": 6,
    "sugar": 6,
    "cost": {
      "dairyEggs": 3.2,
      "protein": 4.5,
      "produce": 2.1,
      "grains": 1.8,
      "fats": 0.7,
      "specialty": 1.2
    }
  },
  "w-mx-035": {
    "servings": 5,
    "kcal": 280,
    "protein": 5,
    "fat": 10,
    "carbs": 40,
    "fiber": 3,
    "sugar": 2,
    "cost": {
      "grains": 0.8,
      "produce": 2.1,
      "fats": 0.3,
      "spices": 0.15
    }
  },
  "w-mx-036": {
    "servings": 6,
    "kcal": 420,
    "protein": 32,
    "fat": 22,
    "carbs": 38,
    "fiber": 10,
    "sugar": 12,
    "cost": {
      "dairyEggs": 0.5,
      "produce": 8.2,
      "grains": 0.3,
      "fats": 0.7,
      "spices": 1.1,
      "specialty": 2.4
    }
  },
  "w-mx-037": {
    "servings": 5,
    "kcal": 420,
    "protein": 22,
    "fat": 28,
    "carbs": 32,
    "fiber": 8,
    "sugar": 10,
    "cost": {
      "dairyEggs": 2.1,
      "produce": 6.45,
      "grains": 1.2,
      "fats": 1.8,
      "spices": 0.75,
      "specialty": 0.9
    }
  },
  "w-mx-038": {
    "servings": 2,
    "kcal": 35,
    "protein": 1,
    "fat": 0,
    "carbs": 8,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "produce": 1.2,
      "spices": 0.15
    }
  },
  "w-mx-039": {
    "servings": 6,
    "kcal": 320,
    "protein": 6,
    "fat": 14,
    "carbs": 42,
    "fiber": 2,
    "sugar": 18,
    "cost": {
      "grains": 0.75,
      "sweeteners": 0.6,
      "dairyEggs": 2.1,
      "specialty": 2.0,
      "fats": 0.15,
      "spices": 0.05
    }
  },
  "w-mx-040": {
    "servings": 16,
    "kcal": 210,
    "protein": 3,
    "fat": 12,
    "carbs": 26,
    "fiber": 1,
    "sugar": 18,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 0.75,
      "fats": 0.6,
      "sweeteners": 0.3,
      "grains": 1.1
    }
  },
  "w-mx-041": {
    "servings": 8,
    "kcal": 520,
    "protein": 32,
    "fat": 32,
    "carbs": 42,
    "fiber": 8,
    "sugar": 6,
    "cost": {
      "produce": 10.5,
      "dairyEggs": 7.2,
      "grains": 2.8,
      "fats": 3.1,
      "spices": 0.9,
      "specialty": 4.5
    }
  },
  "w-mx-042": {
    "servings": 6,
    "kcal": 320,
    "protein": 28,
    "fat": 14,
    "carbs": 32,
    "fiber": 6,
    "sugar": 12,
    "cost": {
      "protein": 4.2,
      "produce": 2.8,
      "fats": 0.6,
      "sweeteners": 0.3,
      "spices": 0.15
    }
  },
  "w-mx-043": {
    "servings": 6,
    "kcal": 420,
    "protein": 38,
    "fat": 22,
    "carbs": 35,
    "fiber": 8,
    "sugar": 6,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 4.8,
      "grains": 1.5,
      "fats": 0.6,
      "spices": 0.75,
      "specialty": 2.0
    }
  },
  "w-mx-044": {
    "servings": 6,
    "kcal": 280,
    "protein": 10,
    "fat": 18,
    "carbs": 22,
    "fiber": 5,
    "sugar": 6,
    "cost": {
      "produce": 3.2,
      "dairyEggs": 2.1,
      "fats": 0.6,
      "spices": 0.3
    }
  },
  "w-mx-045": {
    "servings": 6,
    "kcal": 320,
    "protein": 10,
    "fat": 18,
    "carbs": 35,
    "fiber": 9,
    "sugar": 4,
    "cost": {
      "produce": 3.2,
      "grains": 1.1,
      "fats": 0.95,
      "dairyEggs": 1.4
    }
  },
  "w-mx-046": {
    "servings": 6,
    "kcal": 390,
    "protein": 18,
    "fat": 26,
    "carbs": 17,
    "fiber": 3,
    "sugar": 5,
    "cost": {
      "produce": 5.4,
      "dairyEggs": 5.6,
      "fats": 1.6,
      "grains": 0.4
    }
  },
  "w-mx-048": {
    "servings": 6,
    "kcal": 35,
    "protein": 0,
    "fat": 0,
    "carbs": 9,
    "fiber": 0,
    "sugar": 8,
    "cost": {
      "spices": 0.6,
      "sweeteners": 0.9
    }
  },
  "w-mx-049": {
    "servings": 4,
    "kcal": 320,
    "protein": 34,
    "fat": 15,
    "carbs": 6,
    "fiber": 1,
    "sugar": 1,
    "cost": {
      "protein": 9.0,
      "produce": 1.1,
      "fats": 0.6,
      "grains": 0.2,
      "spices": 0.3
    }
  },
  "w-mx-050": {
    "servings": 4,
    "kcal": 380,
    "protein": 15,
    "fat": 18,
    "carbs": 39,
    "fiber": 3,
    "sugar": 3,
    "cost": {
      "grains": 1.6,
      "dairyEggs": 3.0,
      "produce": 1.7,
      "spices": 0.2
    }
  },
  "w-vn-001": {
    "servings": 5,
    "kcal": 280,
    "protein": 15,
    "fat": 13,
    "carbs": 26,
    "fiber": 4,
    "sugar": 6,
    "cost": {
      "protein": 9,
      "produce": 4,
      "grains": 1.5,
      "dairyEggs": 1.5,
      "spices": 0.3
    }
  },
  "w-vn-002": {
    "servings": 5,
    "kcal": 260,
    "protein": 17,
    "fat": 19,
    "carbs": 5,
    "fiber": 1,
    "sugar": 3,
    "cost": {
      "protein": 6,
      "specialty": 2,
      "produce": 0.8,
      "spices": 0.4
    }
  },
  "w-vn-003": {
    "servings": 5,
    "kcal": 340,
    "protein": 5,
    "fat": 14,
    "carbs": 50,
    "fiber": 1,
    "sugar": 14,
    "cost": {
      "grains": 2,
      "specialty": 2.5,
      "dairyEggs": 1,
      "sweeteners": 0.5,
      "fats": 0.3
    }
  },
  "w-vn-004": {
    "servings": 12,
    "kcal": 380,
    "protein": 6,
    "fat": 14,
    "carbs": 60,
    "fiber": 1,
    "sugar": 28,
    "cost": {
      "grains": 1.5,
      "specialty": 2,
      "sweeteners": 1.2,
      "dairyEggs": 1.2,
      "fats": 0.6
    }
  },
  "w-vn-005": {
    "servings": 5,
    "kcal": 280,
    "protein": 22,
    "fat": 10,
    "carbs": 26,
    "fiber": 2,
    "sugar": 9,
    "cost": {
      "protein": 10,
      "specialty": 1.5,
      "grains": 1,
      "produce": 0.5,
      "fats": 0.5,
      "sweeteners": 0.3,
      "spices": 0.4
    }
  },
  "w-vn-006": {
    "servings": 5,
    "kcal": 380,
    "protein": 6,
    "fat": 9,
    "carbs": 70,
    "fiber": 3,
    "sugar": 35,
    "cost": {
      "sweeteners": 1.5,
      "specialty": 1.5,
      "grains": 1.2,
      "produce": 0.8,
      "fats": 0.4,
      "spices": 0.3
    }
  },
  "w-vn-007": {
    "servings": 5,
    "kcal": 60,
    "protein": 0,
    "fat": 0,
    "carbs": 15,
    "fiber": 1,
    "sugar": 14,
    "cost": {
      "specialty": 1.5,
      "sweeteners": 0.3
    }
  },
  "w-es-001": {
    "servings": 5,
    "kcal": 420,
    "protein": 22,
    "fat": 14,
    "carbs": 55,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "protein": 12,
      "grains": 1.5,
      "produce": 3,
      "specialty": 5,
      "fats": 0.5
    }
  },
  "w-es-002": {
    "servings": 5,
    "kcal": 480,
    "protein": 24,
    "fat": 18,
    "carbs": 55,
    "fiber": 4,
    "sugar": 8,
    "cost": {
      "protein": 6,
      "produce": 4,
      "grains": 1.5,
      "fats": 0.3
    }
  },
  "w-es-003": {
    "servings": 5,
    "kcal": 280,
    "protein": 20,
    "fat": 12,
    "carbs": 22,
    "fiber": 2,
    "sugar": 4,
    "cost": {
      "protein": 9,
      "produce": 2,
      "grains": 1,
      "fats": 0.5
    }
  },
  "w-es-004": {
    "servings": 5,
    "kcal": 180,
    "protein": 20,
    "fat": 10,
    "carbs": 1,
    "fiber": 0,
    "sugar": 0,
    "cost": {
      "protein": 7,
      "produce": 1.5,
      "fats": 0.3
    }
  },
  "w-es-005": {
    "servings": 6,
    "kcal": 220,
    "protein": 6,
    "fat": 9,
    "carbs": 30,
    "fiber": 0,
    "sugar": 28,
    "cost": {
      "dairyEggs": 3,
      "sweeteners": 0.5,
      "spices": 0.8
    }
  },
  "w-es-006": {
    "servings": 6,
    "kcal": 450,
    "protein": 25,
    "fat": 16,
    "carbs": 55,
    "fiber": 14,
    "sugar": 2,
    "cost": {
      "protein": 4,
      "grains": 3,
      "spices": 3.2,
      "fats": 0.3
    }
  },
  "w-es-007": {
    "servings": 5,
    "kcal": 350,
    "protein": 28,
    "fat": 15,
    "carbs": 28,
    "fiber": 4,
    "sugar": 5,
    "cost": {
      "protein": 10,
      "produce": 4,
      "specialty": 2,
      "fats": 0.7
    }
  },
  "w-es-008": {
    "servings": 5,
    "kcal": 380,
    "protein": 5,
    "fat": 20,
    "carbs": 50,
    "fiber": 4,
    "sugar": 1,
    "cost": {
      "produce": 2,
      "fats": 2
    }
  },
  "w-es-009": {
    "servings": 6,
    "kcal": 320,
    "protein": 14,
    "fat": 18,
    "carbs": 22,
    "fiber": 1,
    "sugar": 6,
    "cost": {
      "protein": 5,
      "dairyEggs": 4,
      "grains": 1.5,
      "fats": 0.5
    }
  },
  "w-es-010": {
    "servings": 6,
    "kcal": 350,
    "protein": 8,
    "fat": 18,
    "carbs": 40,
    "fiber": 0,
    "sugar": 25,
    "cost": {
      "dairyEggs": 3,
      "grains": 0.5,
      "sweeteners": 0.4,
      "fats": 1,
      "produce": 0.3
    }
  },
  "w-es-011": {
    "servings": 6,
    "kcal": 240,
    "protein": 7,
    "fat": 8,
    "carbs": 35,
    "fiber": 0,
    "sugar": 30,
    "cost": {
      "dairyEggs": 2.5,
      "sweeteners": 0.5,
      "grains": 1,
      "spices": 0.5
    }
  },
  "w-es-012": {
    "servings": 9,
    "kcal": 380,
    "protein": 10,
    "fat": 22,
    "carbs": 40,
    "fiber": 3,
    "sugar": 34,
    "cost": {
      "specialty": 6,
      "sweeteners": 2,
      "dairyEggs": 0.3
    }
  },
  "w-es-013": {
    "servings": 4,
    "kcal": 180,
    "protein": 4,
    "fat": 9,
    "carbs": 24,
    "fiber": 2,
    "sugar": 3,
    "cost": {
      "grains": 1,
      "produce": 0.5,
      "fats": 0.5
    }
  },
  "w-es-014": {
    "servings": 5,
    "kcal": 220,
    "protein": 3,
    "fat": 9,
    "carbs": 33,
    "fiber": 3,
    "sugar": 4,
    "cost": {
      "produce": 2,
      "fats": 1,
      "spices": 0.3
    }
  },
  "w-es-015": {
    "servings": 5,
    "kcal": 140,
    "protein": 4,
    "fat": 8,
    "carbs": 17,
    "fiber": 4,
    "sugar": 9,
    "cost": {
      "produce": 5,
      "fats": 0.7,
      "spices": 0.3
    }
  },
  "w-es-016": {
    "servings": 6,
    "kcal": 300,
    "protein": 8,
    "fat": 8,
    "carbs": 50,
    "fiber": 1,
    "sugar": 32,
    "cost": {
      "dairyEggs": 2.5,
      "grains": 0.3,
      "sweeteners": 0.4,
      "specialty": 1
    }
  },
  "w-es-017": {
    "servings": 6,
    "kcal": 420,
    "protein": 15,
    "fat": 24,
    "carbs": 35,
    "fiber": 4,
    "sugar": 3,
    "cost": {
      "dairyEggs": 2.5,
      "produce": 3,
      "fats": 1
    }
  },
  "w-es-018": {
    "servings": 7,
    "kcal": 480,
    "protein": 15,
    "fat": 30,
    "carbs": 40,
    "fiber": 4,
    "sugar": 35,
    "cost": {
      "specialty": 10,
      "sweeteners": 0.7,
      "dairyEggs": 1.5,
      "produce": 0.3
    }
  },
  "w-es-019": {
    "servings": 4,
    "kcal": 160,
    "protein": 8,
    "fat": 10,
    "carbs": 8,
    "fiber": 2,
    "sugar": 5,
    "cost": {
      "dairyEggs": 1.2,
      "produce": 2.5,
      "fats": 0.5
    }
  },
};
